apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: example
  labels:
    app: frontend
data:
  TRANSACTIONS_API_ADDR: ledgerwriter:80
  BALANCES_API_ADDR: balancereader:80
  HISTORY_API_ADDR: transactionhistory:80
  CONTACTS_API_ADDR: contacts:80
  USERSERVICE_API_ADDR: userservice:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
  namespace: example
  labels:
    app: frontend
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: testuser
  # All demo user accounts are hardcoded to use the login password 'bankofanthos'
  DEMO_LOGIN_PASSWORD: bankofanthos
