apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
source: |-
  def set_namespace(resource_list):
     set_ns = ""
     for r in resource_list["items"]:
       if r["apiVersion"] == "v1" and r["kind"] == "ConfigMap" and r.get("metadata").get("name") == "kptfile.kpt.dev":
         set_ns = r["data"]["name"]

     if set_ns == "": # missing package context
       return

     for r in resource_list["items"]:
       if r["apiVersion"] == "v1" and r["kind"] == "Namespace":
         r["metadata"]["name"] = set_ns
       if r["metadata"].get("namespace", "") != "":
         r["metadata"]["namespace"] = set_ns

  set_namespace(ctx.resource_list)
